name: validate
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed:latest
    steps:
      - run: zypper --non-interactive install tar xz git sassc ImageMagick nodejs rsvg-convert
      - uses: actions/checkout@v4
      - run: ./scripts/build.sh
      - run: ./scripts/package.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Lyra-Enterprise
          path: Lyra-Enterprise.tar.xz
